//
//  CustomReplacements.swift
//  DyLexAid
//
//  Created by Steinhauer, Jan on 1/27/25.
//

import Foundation

struct CustomReplacements {
    static let replacements: [String: String] = [
        "society": "community",
        "virtuous": "good",
        "faculties": "abilities",
        "subsistence": "support",
        "prejudice": "bias",
        "affections": "feelings",
        "developing": "growing",
        "rational": "reasonable",
        "caprice": "whim",
        "benevolent": "kind",
        "arduous": "hard",
        "expeditious": "quick",
        "obligatory": "required",
        "consequences": "results",
        "eminent": "important",
        "perseverance": "determination",
        "alleviate": "ease",
        "commence": "start",
        "endeavor": "try",
        "obstinate": "stubborn",
        "profound": "deep",
        "articulate": "express",
        "disposition": "attitude",
        "comprehend": "understand",
        "solicit": "ask",
        "endeavoring": "trying",
        "abundant": "plentiful",
        "necessitate": "need",
        "perceive": "see",
        "exceed": "surpass",
        "ameliorate": "improve",
        "proclaim": "announce",
        "gratitude": "thanks",
        "elaborate": "explain",
        "liberate": "free",
        "deduce": "figure out",
        "accumulate": "gather",
        "adjacent": "near",
        "adverse": "bad",
        "advocate": "support",
        "allocate": "assign",
        "alternative": "choice",
        "analyze": "examine",
        "antagonist": "enemy",
        "apparent": "clear",
        "approximate": "close",
        "artificial": "fake",
        "ascertain": "find out",
        "assert": "claim",
        "assistance": "help",
        "attain": "achieve",
        "authorize": "allow",
        "beneficial": "helpful",
        "calculate": "work out",
        "categorize": "sort",
        "circumstance": "situation",
        "coherent": "clear",
        "collaborate": "work together",
        "commend": "praise",
        "comparable": "similar",
        "compensate": "repay",
        "competent": "skilled",
        "comprehensive": "complete",
        "concept": "idea",
        "confer": "discuss",
        "confine": "limit",
        "conform": "follow",
        "contemplate": "think about",
        "contemporary": "modern",
        "contradict": "disagree",
        "convey": "show",
        "criteria": "rules",
        "crucial": "important",
        "culminate": "end",
        "dedicate": "devote",
        "deficient": "lacking",
        "demonstrate": "show",
        "depict": "describe",
        "derive": "get",
        "determine": "decide",
        "detrimental": "harmful",
        "diminish": "lessen",
        "distribute": "share",
        "eliminate": "remove",
        "emphasize": "highlight",
        "enhance": "improve",
        "ensure": "make sure",
        "entire": "whole",
        "equivalent": "equal",
        "establish": "set up",
        "evaluate": "judge",
        "evidence": "proof",
        "exaggerate": "overstate",
        "exclude": "leave out",
        "exhibit": "show",
        "expand": "grow",
        "explicit": "clear",
        "facilitate": "help",
        "feasible": "possible",
        "fluctuate": "change",
        "function": "purpose",
        "generate": "create",
        "guarantee": "promise",
        "hypothesis": "guess",
        "identical": "same",
        "illustrate": "show",
        "immediate": "quick",
        "implement": "use",
        "implicit": "hidden",
        "indicate": "show",
        "indispensable": "essential",
        "inevitable": "unavoidable",
        "infer": "guess",
        "initial": "first",
        "integrate": "combine",
        "intense": "strong",
        "interpret": "explain",
        "intricate": "complex",
        "isolate": "separate",
        "justify": "explain",
        "legitimate": "lawful",
        "maintain": "keep",
        "manifest": "clear",
        "modify": "change",
        "notion": "idea",
        "obtain": "get",
        "omit": "leave out",
        "permanent": "lasting",
        "persist": "continue",
        "precede": "come before",
        "predict": "guess",
        "prevalent": "common",
        "prominent": "important",
        "prosper": "succeed",
        "relinquish": "give up",
        "reside": "live",
        "retain": "keep",
        "sufficient": "enough",
        "sustain": "support",
        "terminate": "end",
        "transform": "change",
        "utilize": "use"
    ]
    
}
